version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: "whatsapp-web.js"
      - dependency-name: "venom-bot"
    assignees:
      - "allburov"
